# Site settings
title: Utah Club Swimming
email: utahclubswimming@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An intercollegiate, competitive club swim team at the University of Utah.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://utahclubswimming.github.io" # the base hostname & protocol for your site

# Usernames
facebook_username:  utahclubswimming
twitter_username:   utahclubswim
instagram_username: utahclubswimming
flickr_username:    utahclubswimming
github_username:    utahclubswimming

# Pages
site_home: index.html

# Navigation
# navigation: [
#     data:
#         - top:
#             - name: 'Home'
#               url:  '/',
#     data:
#         - top:
#             - name: 'About'
#               url:  '/about/',
#     data:
#         - top:
#             - name: 'Our Team'
#               url:  '/team/'
#         - children:
#             [
#                 - name: 'Team'
#                   url:  '/team/',
#                 - name: 'Officers'
#                   url:  '/team/officers/'
#             ]
# ]


# Build settings
markdown: kramdown
