# Site settings
title: Utah Club Swimming
description: An intercollegiate, competitive club swim team at the University of Utah.
baseurl: ""
url: "https://www.utahclubswimming.com"
timezone: America/Denver

# This determines how blog posts are displayed.
permalink: /blog/:year/:month/:day/:title

# Point of contact
# (By default, this is the info listed on the Contact page.)
contact: Ethan Beseris
contact_phone: (801) 554-1274
contact_email: team@utahclubswimming.com

# Usernames
facebook_username:  utahclubswimming
twitter_username:   utahclubswim
instagram_username: utahclubswimming
flickr_username:    utahclubswimming
github_username:    utahclubswimming

# Content locations
asset_url: /assets
image_url: /assets/images
js_url:    /assets/js
fonts_url: /assets/fonts

# Build settings
markdown: kramdown
