# Site settings
title: Utah Club Swimming
email: team@utahclubswimming.com
description: An intercollegiate, competitive club swim team at the University of Utah.
baseurl: ""
url: "https://www.utahclubswimming.com"
permalink: /blog/:year/:month/:day/:title
timezone: America/Denver

# Usernames
facebook_username:  utahclubswimming
twitter_username:   utahclubswim
instagram_username: utahclubswimming
flickr_username:    utahclubswimming
github_username:    utahclubswimming

# Content locations
asset_url: /assets
image_url: /assets/images
js_url:    /assets/js
fonts_url: /assets/fonts

# Build settings
markdown: kramdown
