# Site settings
title: Utah Club Swimming
email: utahclubswimming@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An intercollegiate, competitive club swim team at the University of Utah.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://utahclubswimming.com" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title
timezone: America/Denver

# Usernames
facebook_username:  utahclubswimming
twitter_username:   utahclubswim
instagram_username: utahclubswimming
flickr_username:    utahclubswimming
github_username:    utahclubswimming

# Content locations
asset_url: /assets
image_url: /assets/images
js_url:    /assets/js
fonts_url: /assets/fonts

# Build settings
markdown: kramdown
